# Generated by Django 5.0.4 on 2024-05-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='boolean',
            field=models.BooleanField(default=True, verbose_name='Соглашение про отправку уведомлений на почту'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='icon.png', upload_to='pictures/user_img', verbose_name='Фото пользователя'),
        ),
    ]
