# Generated by Django 5.0.4 on 2024-05-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_boolean_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='boolean',
            field=models.BooleanField(default=False, verbose_name='Соглашение про отправку уведомлений на почту'),
        ),
    ]
