# Generated by Django 5.0.4 on 2024-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Женский пол')], max_length=10, verbose_name='Пол пользова'),
        ),
    ]
