# Generated by Django 5.0.4 on 2024-05-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_alter_course_slug_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
