# Generated by Django 5.0.4 on 2024-05-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_comment_lesson_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.CharField(default='', max_length=100, verbose_name='Видео URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.png', upload_to='course_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(verbose_name='Уникальное название курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(verbose_name='Уникальное название урока'),
        ),
    ]
